// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audio_messages.sql

package database

import (
	"context"
)

const createAudioMessage = `-- name: CreateAudioMessage :one
INSERT INTO audio_messages (id, sender_user_id, file_path, duration)
VALUES (?, ?, ?, ?)
RETURNING id, sender_user_id, file_path, duration, created_at, deleted_at
`

type CreateAudioMessageParams struct {
	ID           string `json:"id"`
	SenderUserID string `json:"sender_user_id"`
	FilePath     string `json:"file_path"`
	Duration     int64  `json:"duration"`
}

func (q *Queries) CreateAudioMessage(ctx context.Context, arg CreateAudioMessageParams) (AudioMessage, error) {
	row := q.db.QueryRowContext(ctx, createAudioMessage,
		arg.ID,
		arg.SenderUserID,
		arg.FilePath,
		arg.Duration,
	)
	var i AudioMessage
	err := row.Scan(
		&i.ID,
		&i.SenderUserID,
		&i.FilePath,
		&i.Duration,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAudioMessage = `-- name: DeleteAudioMessage :exec
DELETE FROM audio_messages
WHERE id = ?
`

func (q *Queries) DeleteAudioMessage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAudioMessage, id)
	return err
}

const getActiveAudioMessages = `-- name: GetActiveAudioMessages :many
SELECT id, sender_user_id, file_path, duration, created_at, deleted_at FROM audio_messages
WHERE deleted_at IS NULL
  AND (
    -- Not older than 7 days
    created_at > datetime('now', '-7 days')
  )
ORDER BY created_at DESC
`

func (q *Queries) GetActiveAudioMessages(ctx context.Context) ([]AudioMessage, error) {
	rows, err := q.db.QueryContext(ctx, getActiveAudioMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AudioMessage{}
	for rows.Next() {
		var i AudioMessage
		if err := rows.Scan(
			&i.ID,
			&i.SenderUserID,
			&i.FilePath,
			&i.Duration,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAudioMessage = `-- name: GetAudioMessage :one
SELECT id, sender_user_id, file_path, duration, created_at, deleted_at FROM audio_messages
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetAudioMessage(ctx context.Context, id string) (AudioMessage, error) {
	row := q.db.QueryRowContext(ctx, getAudioMessage, id)
	var i AudioMessage
	err := row.Scan(
		&i.ID,
		&i.SenderUserID,
		&i.FilePath,
		&i.Duration,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOldOrFullyReceivedMessages = `-- name: GetOldOrFullyReceivedMessages :many
SELECT am.id, am.sender_user_id, am.file_path, am.duration, am.created_at, am.deleted_at
FROM audio_messages am
WHERE am.deleted_at IS NULL
  AND (
    -- Older than 7 days
    am.created_at <= datetime('now', '-7 days')
    OR
    -- All approved users have received it
    (
      SELECT COUNT(DISTINCT u.id)
      FROM users u
      WHERE u.approved = TRUE
    ) = (
      SELECT COUNT(*)
      FROM audio_message_receipts amr
      WHERE amr.audio_message_id = am.id
    )
  )
`

func (q *Queries) GetOldOrFullyReceivedMessages(ctx context.Context) ([]AudioMessage, error) {
	rows, err := q.db.QueryContext(ctx, getOldOrFullyReceivedMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AudioMessage{}
	for rows.Next() {
		var i AudioMessage
		if err := rows.Scan(
			&i.ID,
			&i.SenderUserID,
			&i.FilePath,
			&i.Duration,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAudioMessages = `-- name: ListAudioMessages :many
SELECT id, sender_user_id, file_path, duration, created_at, deleted_at FROM audio_messages
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAudioMessages(ctx context.Context) ([]AudioMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAudioMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AudioMessage{}
	for rows.Next() {
		var i AudioMessage
		if err := rows.Scan(
			&i.ID,
			&i.SenderUserID,
			&i.FilePath,
			&i.Duration,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAudioMessagesBySender = `-- name: ListAudioMessagesBySender :many
SELECT id, sender_user_id, file_path, duration, created_at, deleted_at FROM audio_messages
WHERE sender_user_id = ? AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAudioMessagesBySender(ctx context.Context, senderUserID string) ([]AudioMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAudioMessagesBySender, senderUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AudioMessage{}
	for rows.Next() {
		var i AudioMessage
		if err := rows.Scan(
			&i.ID,
			&i.SenderUserID,
			&i.FilePath,
			&i.Duration,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAudioMessage = `-- name: SoftDeleteAudioMessage :exec
UPDATE audio_messages
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) SoftDeleteAudioMessage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteAudioMessage, id)
	return err
}
