// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type AudioMessage struct {
	ID           string       `json:"id"`
	SenderUserID string       `json:"sender_user_id"`
	FilePath     string       `json:"file_path"`
	Duration     int64        `json:"duration"`
	CreatedAt    time.Time    `json:"created_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}

type AudioMessageReceipt struct {
	ID             int64     `json:"id"`
	AudioMessageID string    `json:"audio_message_id"`
	UserID         string    `json:"user_id"`
	ReceivedAt     time.Time `json:"received_at"`
}

type GooseDbVersion struct {
	ID        int64        `json:"id"`
	VersionID int64        `json:"version_id"`
	IsApplied int64        `json:"is_applied"`
	Tstamp    sql.NullTime `json:"tstamp"`
}

type SqliteSequence struct {
	Name interface{} `json:"name"`
	Seq  interface{} `json:"seq"`
}

type User struct {
	ID           string       `json:"id"`
	Name         string       `json:"name"`
	DeviceIDHash string       `json:"device_id_hash"`
	Approved     bool         `json:"approved"`
	LastActive   sql.NullTime `json:"last_active"`
	Role         string       `json:"role"`
	CreatedAt    time.Time    `json:"created_at"`
}
