// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type AudioMessage struct {
	ID           int64        `json:"id"`
	SenderUserID int64        `json:"sender_user_id"`
	FilePath     string       `json:"file_path"`
	Duration     int64        `json:"duration"`
	CreatedAt    time.Time    `json:"created_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}

type AudioMessageReceipt struct {
	ID             int64     `json:"id"`
	AudioMessageID int64     `json:"audio_message_id"`
	UserID         int64     `json:"user_id"`
	ReceivedAt     time.Time `json:"received_at"`
}

type User struct {
	ID         int64        `json:"id"`
	Name       string       `json:"name"`
	DeviceID   string       `json:"device_id"`
	Approved   int64        `json:"approved"`
	LastActive sql.NullTime `json:"last_active"`
	CreatedAt  time.Time    `json:"created_at"`
}
