// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: receipts.sql

package database

import (
	"context"
)

const countReceiptsByMessage = `-- name: CountReceiptsByMessage :one
SELECT COUNT(*) as count
FROM audio_message_receipts
WHERE audio_message_id = ?
`

func (q *Queries) CountReceiptsByMessage(ctx context.Context, audioMessageID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReceiptsByMessage, audioMessageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReceipt = `-- name: CreateReceipt :one
INSERT INTO audio_message_receipts (audio_message_id, user_id)
VALUES (?, ?)
RETURNING id, audio_message_id, user_id, received_at
`

type CreateReceiptParams struct {
	AudioMessageID string `json:"audio_message_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) CreateReceipt(ctx context.Context, arg CreateReceiptParams) (AudioMessageReceipt, error) {
	row := q.db.QueryRowContext(ctx, createReceipt, arg.AudioMessageID, arg.UserID)
	var i AudioMessageReceipt
	err := row.Scan(
		&i.ID,
		&i.AudioMessageID,
		&i.UserID,
		&i.ReceivedAt,
	)
	return i, err
}

const getReceipt = `-- name: GetReceipt :one
SELECT id, audio_message_id, user_id, received_at FROM audio_message_receipts
WHERE audio_message_id = ? AND user_id = ?
`

type GetReceiptParams struct {
	AudioMessageID string `json:"audio_message_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) GetReceipt(ctx context.Context, arg GetReceiptParams) (AudioMessageReceipt, error) {
	row := q.db.QueryRowContext(ctx, getReceipt, arg.AudioMessageID, arg.UserID)
	var i AudioMessageReceipt
	err := row.Scan(
		&i.ID,
		&i.AudioMessageID,
		&i.UserID,
		&i.ReceivedAt,
	)
	return i, err
}

const getUnreceivedMessagesByUser = `-- name: GetUnreceivedMessagesByUser :many
SELECT am.id, am.sender_user_id, am.file_path, am.duration, am.created_at, am.deleted_at
FROM audio_messages am
WHERE am.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM audio_message_receipts amr
    WHERE amr.audio_message_id = am.id
      AND amr.user_id = ?
  )
ORDER BY am.created_at DESC
`

func (q *Queries) GetUnreceivedMessagesByUser(ctx context.Context) ([]AudioMessage, error) {
	rows, err := q.db.QueryContext(ctx, getUnreceivedMessagesByUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AudioMessage{}
	for rows.Next() {
		var i AudioMessage
		if err := rows.Scan(
			&i.ID,
			&i.SenderUserID,
			&i.FilePath,
			&i.Duration,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiptsByMessage = `-- name: ListReceiptsByMessage :many
SELECT id, audio_message_id, user_id, received_at FROM audio_message_receipts
WHERE audio_message_id = ?
ORDER BY received_at DESC
`

func (q *Queries) ListReceiptsByMessage(ctx context.Context, audioMessageID string) ([]AudioMessageReceipt, error) {
	rows, err := q.db.QueryContext(ctx, listReceiptsByMessage, audioMessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AudioMessageReceipt{}
	for rows.Next() {
		var i AudioMessageReceipt
		if err := rows.Scan(
			&i.ID,
			&i.AudioMessageID,
			&i.UserID,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiptsByUser = `-- name: ListReceiptsByUser :many
SELECT id, audio_message_id, user_id, received_at FROM audio_message_receipts
WHERE user_id = ?
ORDER BY received_at DESC
`

func (q *Queries) ListReceiptsByUser(ctx context.Context, userID string) ([]AudioMessageReceipt, error) {
	rows, err := q.db.QueryContext(ctx, listReceiptsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AudioMessageReceipt{}
	for rows.Next() {
		var i AudioMessageReceipt
		if err := rows.Scan(
			&i.ID,
			&i.AudioMessageID,
			&i.UserID,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
