// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
)

const approveUser = `-- name: ApproveUser :exec
UPDATE users
SET approved = 1
WHERE id = ?
`

func (q *Queries) ApproveUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, approveUser, id)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, device_id, approved)
VALUES (?, ?, ?)
RETURNING id, name, device_id, approved, last_active, created_at
`

type CreateUserParams struct {
	Name     string `json:"name"`
	DeviceID string `json:"device_id"`
	Approved int64  `json:"approved"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Name, arg.DeviceID, arg.Approved)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeviceID,
		&i.Approved,
		&i.LastActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, name, device_id, approved, last_active, created_at FROM users
WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeviceID,
		&i.Approved,
		&i.LastActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByDeviceID = `-- name: GetUserByDeviceID :one
SELECT id, name, device_id, approved, last_active, created_at FROM users
WHERE device_id = ?
`

func (q *Queries) GetUserByDeviceID(ctx context.Context, deviceID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByDeviceID, deviceID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeviceID,
		&i.Approved,
		&i.LastActive,
		&i.CreatedAt,
	)
	return i, err
}

const listApprovedUsers = `-- name: ListApprovedUsers :many
SELECT id, name, device_id, approved, last_active, created_at FROM users
WHERE approved = 1
ORDER BY created_at DESC
`

func (q *Queries) ListApprovedUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listApprovedUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DeviceID,
			&i.Approved,
			&i.LastActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, device_id, approved, last_active, created_at FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DeviceID,
			&i.Approved,
			&i.LastActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserLastActive = `-- name: UpdateUserLastActive :exec
UPDATE users
SET last_active = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateUserLastActive(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateUserLastActive, id)
	return err
}
